version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
  # Enable version updates for npm workspaces
  - package-ecosystem: "npm"
    directory: "/modules/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
      
  - package-ecosystem: "npm"
    directory: "/modules/compiler"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
      
  - package-ecosystem: "npm"
    directory: "/modules/console"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
      
  - package-ecosystem: "npm"
    directory: "/modules/engine"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
      
  - package-ecosystem: "npm"
    directory: "/console-ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"